'use strict';

// tests for createSetting
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('createSetting', '/features/server/settings/create.js', 'createSetting');

describe('createSetting', () => {
  before((done) => {
    done();
  });

  it('Should return the same body', () => {
    const body = {"body": `{"setting": "test"}`}
    return wrapped.run(body).then((response) => {
      expect(response).to.be.body;
    });
  });
});
