'use strict';

// tests for createSetting
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('createSetting', '/features/server/settings/create.js', 'createSetting');

describe('createSetting', () => {
  before((done) => {
    done();
  });

  it('Should return the same body', () => {
    return wrapped.run(`{"body": {"setting": "test"}}`).then((response) => {
      console.log('response:', response)
      expect(response).to.not.be.empty;
    });
  });
});
